[build]
zig = "2.17" # Use GLIBC 2.17 for compatibility with older Linux distributions

[target.x86_64-unknown-linux-gnu]
zig = "2.17" # Use GLIBC 2.17 for compatibility with older Linux distributions

[target.aarch64-unknown-linux-gnu]
zig = "2.17" # Use GLIBC 2.17 for compatibility with older Linux distributions
