name: 📊 Benchmarks
on:
  push: {}

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        run: |
          rustup toolchain install stable
          rustup default stable

      - name: Build
        run: cargo build --release

      - run: make bench
