name: Rust Build

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable  # You can specify a version like '1.60.0' if needed
          override: true

      - name: Build
        run: cargo build --release

      - run: cargo install wasm-pack
      - run: wasm-pack build --target nodejs

      - run: make bench
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: make smoketest
