name: Linting check

on:
  workflow_call: {}
  push: {}

jobs:
  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        run: |
          rustup toolchain install stable
          rustup default stable
          rustup component add rustfmt clippy

      # Formatting
      - name: Run rustfmt
        run: cargo fmt -- --check

      # Linting
      - name: Run clippy
        run: cargo clippy
