name: 🧹 Linting check

on:
  workflow_call: {}
  push: {}

permissions:
  contents: read

jobs:
  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Rust
        run: |
          rustup toolchain install stable
          rustup default stable
          rustup component add rustfmt

      - name: Run rustfmt
        run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Rust
        run: |
          rustup toolchain install stable
          rustup default stable
          rustup component add clippy

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
