name: 🔥 Smoke Tests

on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        run: |
          rustup toolchain install stable
          rustup default stable

      - run: cargo install wasm-pack
      - run: wasm-pack build --target nodejs --features js

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - uses: denoland/setup-deno@4606d5cc6fb3f673efd4f594850e3f4b3e9d29cd # v2
        with:
          deno-version: v2.x
      - run: make smoketest
