name: Test

on:
  push:

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - run: |
          rustup update --no-self-update stable
          rustup default stable
          rustup component add --toolchain stable rust-src
          cargo build --release
