name: Test

on:
  push:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - run: |
          rustup update --no-self-update stable
          rustup default stable
          cargo install cross --git https://github.com/cross-rs/cross
          cross build --target x86_64-unknown-linux-gnu --release
          ls target/x86_64-unknown-linux-gnu/release
          objdump -T target/x86_64-unknown-linux-gnu/release/libzen_internals.so | grep GLIBC

      - uses: actions/upload-artifact@v3
        with:
          name: linux-binaries
          path: target/x86_64-unknown-linux-gnu/release/libzen_internals.so
