name: Test

on:
  push:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: mlugg/setup-zig@v1

      - run: |
          rustup update --no-self-update stable
          rustup default stable
          cargo install zigbuild
          cross zigbuild --target x86_64-unknown-linux-gnu.2.17 --release
          ls target/x86_64-unknown-linux-gnu/release
          objdump -T target/x86_64-unknown-linux-gnu/release/libzen_internals.so | grep GLIBC

      - uses: actions/upload-artifact@v3
        with:
          name: linux-binaries
          path: target/x86_64-unknown-linux-gnu/release/libzen_internals.so
