name: Test

on:
  push:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - run: |
          rustup update --no-self-update stable
          rustup default stable
          cargo install cross
          cross run --target x86_64-unknown-linux-gnu
