name: Test

on:
  push:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        run: rustup toolchain install stable

      - name: Build for linux
        run:
          cargo build --release --target x86_64-unknown-linux-musl

  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        run: rustup toolchain install stable

      - name: Build for Linux
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y gcc-aarch64-linux-gnu musl-tools
          cargo build --release --target aarch64-unknown-linux-musl
