name: Rust Unit Tests

on:
  workflow_call: {}
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        run: |
          rustup toolchain install stable
          rustup default stable
          rustup component add llvm-tools-preview

      - name: Install code coverage tool
        uses: taiki-e/install-action@11f460a4042c6aedd95853e41f4eb4f10459fc5d # cargo-llvm-cov

      - name: Run tests
        run: cargo llvm-cov

      - name: Generate coverage report
        run: cargo llvm-cov report --lcov --output-path target/lcov.info

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
        # Makes sure that we don't try to upload coverage if called from another workflow (e.g. publish.yml)
        if: ${{ github.event_name != 'workflow_call' }}
        with:
          fail_ci_if_error: true
          files: ./target/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
