name: Rust Unit Tests

on:
  workflow_call: {}
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        run: |
          rustup toolchain install stable
          rustup default stable
          rustup component add llvm-tools-preview

      - name: Install code coverage tool
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Run tests
        run: cargo llvm-cov run

      - name: Generate coverage report
        run: cargo llvm-cov report --lcov --output-path target/lcov.info
