name: Rust Unit Tests

on:
  workflow_call: {}
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable  # You can specify a version like '1.60.0' or 'nightly'
          override: true

      - name: Run tests
        run: cargo test
