name: Windows

on:
  push: {}

jobs:
  build-windows-arm:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest rust toolchain
        run: |
          rustup update --no-self-update stable
          rustup default stable
          rustup target add aarch64-pc-windows-msvc
      - name: Build for windows arm
        run: cargo build --release --target aarch64-pc-windows-msvc

      - name: Prepare release
        shell: pwsh
        run: |
          Set-Location target/aarch64-pc-windows-msvc/release
          $FILE = "libzen_internals_aarch64-pc-windows-msvc.dll"
          Move-Item "zen_internals.dll" $FILE
          New-Item -ItemType File -Path "$FILE.sha256sum" | Out-Null
          Set-ItemProperty -Path "$FILE.sha256sum" -Name IsReadOnly -Value $false
          # Generate SHA256 checksum and write it in lowercase
          Get-FileHash -Algorithm SHA256 -Path $FILE | ForEach-Object { "$($_.Hash.ToLower()) $FILE" } > "$FILE.sha256sum"
          # Fix line endings
          (Get-Content "$FILE.sha256sum") -replace "`r`n", "`n" | Set-Content "$FILE.sha256sum"
      - name: Store the .dll file and sha256sum file
        uses: actions/upload-artifact@v4
        with:
          name: windows-binaries-arm
          path: target/aarch64-pc-windows-msvc/release/libzen_internals_*
