name: Windows

on:
  push: {}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Rust
        run: |
          rustup update --no-self-update stable
          rustup default stable
          rustup target add aarch64-pc-windows-msvc
      - name: Build for windows
        run: cargo build --release --target aarch64-pc-windows-msvc
      - run: ls -l target/aarch64-pc-windows-msvc/release
      - name: Store the .dll file
        uses: actions/upload-artifact@v3
        with:
          name: windows-binaries
          path: target/aarch64-pc-windows-msvc/release/zen_internals.dll
